site_name: Golang Helper
site_url: https://abhishekghoshh.github.io/golang-helper

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Basics: basics.md
  - Control Flow: control-flow.md
  - Functions: functions.md
  - Pointers: pointers.md
  - Structs & Methods: structs-and-methods.md
  - Arrays, Slices & Maps: arrays-slices-maps.md
  - Concurrency: concurrency.md
  - Interfaces: interfaces.md
  - Modules: modules.md
  - Bytes & Encoding: bytes-and-encoding.md
  - Type Conversions: type-conversions.md
  - Generics: generics.md
  - File I/O: file-io.md
  - Testing: testing.md
  - Online Resources: online-resources.md
  - Popular Libraries: popular-libraries.md
  - Project Structure: project-structure.md
  - Links: links.md






theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - social
  - search
  - mkdocs-pdf

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/abhishekghoshh
    - icon: fontawesome/brands/twitter
      link: https://x.com/abhishek_ghoshh
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/abhishek-ghosh-220679132/

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


copyright: |
  &copy; 2025 <a href="https://github.com/abhishekghoshh"  target="_blank" rel="noopener">Abhishek Ghosh</a>
