package main

func main() {
	// introduction.HellowWorld()
	// introduction.Variables()
	// introduction.TypeConversions()
	// introduction.Types()
	// introduction.FlowControl()
	// introduction.Functions()
	// introduction.VariadicFunctions()
	// introduction.Recursion()
	// introduction.Defer()
	// introduction.PanicAndRecover()
	// introduction.Clousures()
	// introduction.Pointers()
	// introduction.Structs()
	// introduction.StructEmbedding()
	// introduction.Interfaces()
	// introduction.Errors()
	// introduction.Readers()
	// introduction.Generics()

	// strings.StringAndRunes()
	// strings.StringBuilers()
	// strings.Stringfunctions()
	// strings.StringFormatting()
	// strings.RegularExperssions()
	// strings.TestTemplates()

	// collections.Arrays()
	// collections.Slices()
	// collections.Maps()
	// collections.Ranges()
	// collections.Sorting()
	// collections.CustomSorting()
	// collections.LinkedLists()
	// collections.OrderedMaps()

	// concurrency.GoRoutines()
	// concurrency.Channels()
	// concurrency.ChannelBuffering()
	// concurrency.ChannelSynchronization()
	// concurrency.ChannelDirections()
	// concurrency.Selects()
	// concurrency.Timeouts()
	// concurrency.NonBlockingChannelOperation()
	// concurrency.ClosingChannel()
	// concurrency.RangeOverChannels()
	// concurrency.Timers()
	// concurrency.Tickers()
	// concurrency.WorkerPools()
	// concurrency.WaitGroups()
	// concurrency.RateLimitting()
	// concurrency.AtomicCounters()
	// concurrency.Mutexes()
	// concurrency.StatefullGoRoutines()
}
