package main

import (
	"basics/files"
)

func main() {
	// introduction.HellowWorld()
	// introduction.Variables()
	// introduction.TypeConversions()
	// introduction.Types()
	// introduction.FlowControl()
	// introduction.Functions()
	// introduction.VariadicFunctions()
	// introduction.Recursion()
	// introduction.Defer()
	// introduction.PanicAndRecover()
	// introduction.Clousures()
	// introduction.Pointers()
	// introduction.Structs()
	// introduction.TestCustomStructTagValidations()
	// introduction.StructEmbedding()
	// introduction.Interfaces()
	// introduction.Errors()
	// introduction.Readers()
	// introduction.Generics()
	// introduction.TestCustomDefaultParameterInFunctionArgument()

	// strings.StringAndRunes()
	// strings.StringBuilers()
	// strings.Stringfunctions()
	// strings.StringFormatting()
	// strings.RegularExperssions()
	// strings.TestTemplates()

	// collections.Arrays()
	// collections.Slices()
	// collections.Maps()
	// collections.Ranges()
	// collections.Sorting()
	// collections.CustomSorting()
	// collections.LinkedLists()
	// collections.OrderedMaps()

	// concurrency.GoRoutines()
	// concurrency.Channels()
	// concurrency.ChannelBuffering()
	// concurrency.ChannelSynchronization()
	// concurrency.ChannelDirections()
	// concurrency.Selects()
	// concurrency.Timeouts()
	// concurrency.NonBlockingChannelOperation()
	// concurrency.ClosingChannel()
	// concurrency.RangeOverChannels()
	// concurrency.Timers()
	// concurrency.Tickers()
	// concurrency.WorkerPools()
	// concurrency.WaitGroups()
	// concurrency.RateLimitting()
	// concurrency.AtomicCounters()
	// concurrency.Mutexes()
	// concurrency.StatefullGoRoutines()

	// serializing.TestJSONHandling()
	// serializing.TestXMLHandling()

	// times.Times()
	// times.Epochs()
	// times.TimeFormatting()

	// utility.RandomNumberGenerator()
	// utility.NumberParsing()
	// utility.URLParsing()
	// utility.SHA256Hashing()
	// utility.Base64Encoding()
	// utility.Reflections()

	files.CatFile()
	// files.ReadingFiles()
	// files.WritingFiles()
	// files.SaveRetrieveAndAppend()
	// files.LineFilters()
	// files.FilePaths()
	// files.Directories()
	// files.TemporaryFilesAndDirectories()
	// files.EmbeddedDirective()

	// testing file

	// commandline.CommandLineArguments()
	// commandline.CommandLineFlags()
	// commandline.CommandLineSubCommands()
	// commandline.EnvironmentVariables()

	// loggings.Loggings()

	// http.HTTPClient()
	// http.HTTPServer()
	// http.Context()
	// http.CustomHTTPWritter()

	// process.DoSpawningProcess()
	// process.DoExecingProcess()
	// process.DoSignals()
	// process.DoExit()
}
