// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: same_level_message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SameLevelEnumOne int32

const (
	SameLevelEnumOne_ENUM_ONE_UNSPECIFIED SameLevelEnumOne = 0
)

// Enum value maps for SameLevelEnumOne.
var (
	SameLevelEnumOne_name = map[int32]string{
		0: "ENUM_ONE_UNSPECIFIED",
	}
	SameLevelEnumOne_value = map[string]int32{
		"ENUM_ONE_UNSPECIFIED": 0,
	}
)

func (x SameLevelEnumOne) Enum() *SameLevelEnumOne {
	p := new(SameLevelEnumOne)
	*p = x
	return p
}

func (x SameLevelEnumOne) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SameLevelEnumOne) Descriptor() protoreflect.EnumDescriptor {
	return file_same_level_message_proto_enumTypes[0].Descriptor()
}

func (SameLevelEnumOne) Type() protoreflect.EnumType {
	return &file_same_level_message_proto_enumTypes[0]
}

func (x SameLevelEnumOne) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SameLevelEnumOne.Descriptor instead.
func (SameLevelEnumOne) EnumDescriptor() ([]byte, []int) {
	return file_same_level_message_proto_rawDescGZIP(), []int{0}
}

type SameLevelMessageOne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SameLevelMessageOne) Reset() {
	*x = SameLevelMessageOne{}
	if protoimpl.UnsafeEnabled {
		mi := &file_same_level_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SameLevelMessageOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SameLevelMessageOne) ProtoMessage() {}

func (x *SameLevelMessageOne) ProtoReflect() protoreflect.Message {
	mi := &file_same_level_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SameLevelMessageOne.ProtoReflect.Descriptor instead.
func (*SameLevelMessageOne) Descriptor() ([]byte, []int) {
	return file_same_level_message_proto_rawDescGZIP(), []int{0}
}

type MessageTwo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	One *SameLevelMessageOne `protobuf:"bytes,1,opt,name=one,proto3" json:"one,omitempty"`
	Two SameLevelEnumOne     `protobuf:"varint,2,opt,name=two,proto3,enum=SameLevelEnumOne" json:"two,omitempty"`
}

func (x *MessageTwo) Reset() {
	*x = MessageTwo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_same_level_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageTwo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTwo) ProtoMessage() {}

func (x *MessageTwo) ProtoReflect() protoreflect.Message {
	mi := &file_same_level_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTwo.ProtoReflect.Descriptor instead.
func (*MessageTwo) Descriptor() ([]byte, []int) {
	return file_same_level_message_proto_rawDescGZIP(), []int{1}
}

func (x *MessageTwo) GetOne() *SameLevelMessageOne {
	if x != nil {
		return x.One
	}
	return nil
}

func (x *MessageTwo) GetTwo() SameLevelEnumOne {
	if x != nil {
		return x.Two
	}
	return SameLevelEnumOne_ENUM_ONE_UNSPECIFIED
}

var File_same_level_message_proto protoreflect.FileDescriptor

var file_same_level_message_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x61, 0x6d, 0x65, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x61,
	0x6d, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x6e,
	0x65, 0x22, 0x59, 0x0a, 0x0a, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x77, 0x6f, 0x12,
	0x26, 0x0a, 0x03, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x53,
	0x61, 0x6d, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f,
	0x6e, 0x65, 0x52, 0x03, 0x6f, 0x6e, 0x65, 0x12, 0x23, 0x0a, 0x03, 0x74, 0x77, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x53, 0x61, 0x6d, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x45, 0x6e, 0x75, 0x6d, 0x4f, 0x6e, 0x65, 0x52, 0x03, 0x74, 0x77, 0x6f, 0x2a, 0x2c, 0x0a, 0x10,
	0x53, 0x61, 0x6d, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x4f, 0x6e, 0x65,
	0x12, 0x18, 0x0a, 0x14, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x4f, 0x4e, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x61,
	0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_same_level_message_proto_rawDescOnce sync.Once
	file_same_level_message_proto_rawDescData = file_same_level_message_proto_rawDesc
)

func file_same_level_message_proto_rawDescGZIP() []byte {
	file_same_level_message_proto_rawDescOnce.Do(func() {
		file_same_level_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_same_level_message_proto_rawDescData)
	})
	return file_same_level_message_proto_rawDescData
}

var file_same_level_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_same_level_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_same_level_message_proto_goTypes = []interface{}{
	(SameLevelEnumOne)(0),       // 0: SameLevelEnumOne
	(*SameLevelMessageOne)(nil), // 1: SameLevelMessageOne
	(*MessageTwo)(nil),          // 2: MessageTwo
}
var file_same_level_message_proto_depIdxs = []int32{
	1, // 0: MessageTwo.one:type_name -> SameLevelMessageOne
	0, // 1: MessageTwo.two:type_name -> SameLevelEnumOne
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_same_level_message_proto_init() }
func file_same_level_message_proto_init() {
	if File_same_level_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_same_level_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SameLevelMessageOne); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_same_level_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageTwo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_same_level_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_same_level_message_proto_goTypes,
		DependencyIndexes: file_same_level_message_proto_depIdxs,
		EnumInfos:         file_same_level_message_proto_enumTypes,
		MessageInfos:      file_same_level_message_proto_msgTypes,
	}.Build()
	File_same_level_message_proto = out.File
	file_same_level_message_proto_rawDesc = nil
	file_same_level_message_proto_goTypes = nil
	file_same_level_message_proto_depIdxs = nil
}
