// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: scalar_types.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScalarTypes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// INTEGERS
	One   int32  `protobuf:"varint,1,opt,name=one,proto3" json:"one,omitempty"`
	Two   int64  `protobuf:"varint,2,opt,name=two,proto3" json:"two,omitempty"`
	Three uint32 `protobuf:"varint,3,opt,name=three,proto3" json:"three,omitempty"`
	Four  uint64 `protobuf:"varint,4,opt,name=four,proto3" json:"four,omitempty"`
	Five  int32  `protobuf:"zigzag32,5,opt,name=five,proto3" json:"five,omitempty"`
	Six   int64  `protobuf:"zigzag64,6,opt,name=six,proto3" json:"six,omitempty"`
	Seven uint32 `protobuf:"fixed32,7,opt,name=seven,proto3" json:"seven,omitempty"`
	Eight uint64 `protobuf:"fixed64,8,opt,name=eight,proto3" json:"eight,omitempty"`
	Nine  int32  `protobuf:"fixed32,9,opt,name=nine,proto3" json:"nine,omitempty"`
	Ten   int64  `protobuf:"fixed64,10,opt,name=ten,proto3" json:"ten,omitempty"`
	// FLOATING POINTS
	Eleven float64 `protobuf:"fixed64,11,opt,name=eleven,proto3" json:"eleven,omitempty"`
	Twelve float32 `protobuf:"fixed32,12,opt,name=twelve,proto3" json:"twelve,omitempty"`
	// OTHERS
	Thirteen bool   `protobuf:"varint,13,opt,name=thirteen,proto3" json:"thirteen,omitempty"`
	Fourteen []byte `protobuf:"bytes,14,opt,name=fourteen,proto3" json:"fourteen,omitempty"`
	Fifteen  string `protobuf:"bytes,15,opt,name=fifteen,proto3" json:"fifteen,omitempty"`
}

func (x *ScalarTypes) Reset() {
	*x = ScalarTypes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scalar_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScalarTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarTypes) ProtoMessage() {}

func (x *ScalarTypes) ProtoReflect() protoreflect.Message {
	mi := &file_scalar_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarTypes.ProtoReflect.Descriptor instead.
func (*ScalarTypes) Descriptor() ([]byte, []int) {
	return file_scalar_types_proto_rawDescGZIP(), []int{0}
}

func (x *ScalarTypes) GetOne() int32 {
	if x != nil {
		return x.One
	}
	return 0
}

func (x *ScalarTypes) GetTwo() int64 {
	if x != nil {
		return x.Two
	}
	return 0
}

func (x *ScalarTypes) GetThree() uint32 {
	if x != nil {
		return x.Three
	}
	return 0
}

func (x *ScalarTypes) GetFour() uint64 {
	if x != nil {
		return x.Four
	}
	return 0
}

func (x *ScalarTypes) GetFive() int32 {
	if x != nil {
		return x.Five
	}
	return 0
}

func (x *ScalarTypes) GetSix() int64 {
	if x != nil {
		return x.Six
	}
	return 0
}

func (x *ScalarTypes) GetSeven() uint32 {
	if x != nil {
		return x.Seven
	}
	return 0
}

func (x *ScalarTypes) GetEight() uint64 {
	if x != nil {
		return x.Eight
	}
	return 0
}

func (x *ScalarTypes) GetNine() int32 {
	if x != nil {
		return x.Nine
	}
	return 0
}

func (x *ScalarTypes) GetTen() int64 {
	if x != nil {
		return x.Ten
	}
	return 0
}

func (x *ScalarTypes) GetEleven() float64 {
	if x != nil {
		return x.Eleven
	}
	return 0
}

func (x *ScalarTypes) GetTwelve() float32 {
	if x != nil {
		return x.Twelve
	}
	return 0
}

func (x *ScalarTypes) GetThirteen() bool {
	if x != nil {
		return x.Thirteen
	}
	return false
}

func (x *ScalarTypes) GetFourteen() []byte {
	if x != nil {
		return x.Fourteen
	}
	return nil
}

func (x *ScalarTypes) GetFifteen() string {
	if x != nil {
		return x.Fifteen
	}
	return ""
}

var File_scalar_types_proto protoreflect.FileDescriptor

var file_scalar_types_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd5, 0x02, 0x0a, 0x0b, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6f, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x77, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x77, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x68, 0x72, 0x65,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x68, 0x72, 0x65, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x6f, 0x75, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x66, 0x6f,
	0x75, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x11,
	0x52, 0x04, 0x66, 0x69, 0x76, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x78, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x12, 0x52, 0x03, 0x73, 0x69, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x76, 0x65,
	0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x07, 0x52, 0x05, 0x73, 0x65, 0x76, 0x65, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x06, 0x52, 0x05, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69, 0x6e, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0f, 0x52, 0x04, 0x6e, 0x69, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x65, 0x6e, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x10, 0x52, 0x03, 0x74, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6c,
	0x65, 0x76, 0x65, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x65, 0x6c, 0x65, 0x76,
	0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x77, 0x65, 0x6c, 0x76, 0x65, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x06, 0x74, 0x77, 0x65, 0x6c, 0x76, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x68,
	0x69, 0x72, 0x74, 0x65, 0x65, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x74, 0x68,
	0x69, 0x72, 0x74, 0x65, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x75, 0x72, 0x74, 0x65,
	0x65, 0x6e, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x66, 0x6f, 0x75, 0x72, 0x74, 0x65,
	0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x66, 0x74, 0x65, 0x65, 0x6e, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x66, 0x74, 0x65, 0x65, 0x6e, 0x42, 0x0c, 0x5a, 0x0a,
	0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_scalar_types_proto_rawDescOnce sync.Once
	file_scalar_types_proto_rawDescData = file_scalar_types_proto_rawDesc
)

func file_scalar_types_proto_rawDescGZIP() []byte {
	file_scalar_types_proto_rawDescOnce.Do(func() {
		file_scalar_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_scalar_types_proto_rawDescData)
	})
	return file_scalar_types_proto_rawDescData
}

var file_scalar_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_scalar_types_proto_goTypes = []interface{}{
	(*ScalarTypes)(nil), // 0: ScalarTypes
}
var file_scalar_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_scalar_types_proto_init() }
func file_scalar_types_proto_init() {
	if File_scalar_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scalar_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScalarTypes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scalar_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scalar_types_proto_goTypes,
		DependencyIndexes: file_scalar_types_proto_depIdxs,
		MessageInfos:      file_scalar_types_proto_msgTypes,
	}.Build()
	File_scalar_types_proto = out.File
	file_scalar_types_proto_rawDesc = nil
	file_scalar_types_proto_goTypes = nil
	file_scalar_types_proto_depIdxs = nil
}
